### PR TITLE
Make jenkins-slave.exe work on Server 2012

### PR DESCRIPTION
**Pull request by daniel-beck**
Untested, got this from a comment to https://wiki.jenkins-ci.org/display/JENKINS/Windows+slaves+Plugin

### CODE REVIEW

**Comment by daniel-beck** [comment]
@oleg-nenashev Maybe this is something you could verify? Do you still have your Windows (e.g. winsw) env?

**Comment by oleg-nenashev** [comment]
I have 1 Winserver 2012, so I can do it

**Comment by oleg-nenashev** [comment]
BTW I doubt such approach will work for winsw in general. Needs an investigation

**Comment by sakamotodesu** [comment]
I hope that it will be merged.
If more investigation is necessary, I can test on some Windows versions.

**Comment by kohsuke** [comment]
I vouch for this change as well. See https://github.com/kohsuke/winsw#net-runtime-40

**Pull request merged**
