### PR TITLE
[JENKINS-42745] - Windows Agent Installer should generate valid jenkins-slave.xml for old APIs

### PR DESCRIPTION
**Pull request by oleg-nenashev**
This change is maybe quite over-engineered, but this engine allows retaining the backward compatibility of the configuration generation logic.
Then this engine can be reused in plugins like Windows Agents Plugin (FKA Windows Slaves Plugin).

https://issues.jenkins-ci.org/browse/JENKINS-42745

@reviewbybees

### CODE REVIEW

**Comment by jglick** [comment]
Sounds fine in principle but is there a downstream PR in `windows-slaves-plugin` showing it being used?

**Comment by oleg-nenashev** [comment]
@jglick not for now.
This change is not RFE, it is a regression bugfix in the public API in the core module. But yes, there is no known usages of this API

**Comment by oleg-nenashev** [comment]
@jglick ping. I am still not convinced I need an example of API usage for the API, which used to be public API in the core: https://github.com/jenkinsci/windows-slave-installer-module/blob/windows-slave-installer-1.6/src/main/java/org/jenkinsci/modules/windows_slave_installer/WindowsSlaveInstaller.java#L141 . Do you disagree?

**Comment by oleg-nenashev** [comment]
@jglick Dead code for now, though I would like to streamline Windows Agents plugin at some point. (Though it would be great to merge this module into the plugin, mission impossible)

@reviewbybees done

**Pull request merged**
